# cd ~/.brewfile/Brewfile
# brew bundle
cask_args appdir: '/Applications'
tap 'caskroom/cask'

brew 'zsh'
brew 'go'
brew 'ghq'
brew 'macvim'
brew 'wget'
brew 'make'
brew 'htop'
brew 'tmux'
brew 'zplug'

cask 'google-japanese-ime'
cask 'iterm2'
cask 'shiftit'
cask 'google-chrome'
cask 'firefox'
cask 'vivaldi'
cask 'fork'
cask 'virtualbox'
cask 'vagrant'
cask 'vagrant-manager'
cask 'visual-studio-code'
